### ISSUE TITLE
Stalled data after executing (nested) mutation

### ISSUE THREAD

**Issue by akoenig** [graphcool/http-link-dataloader#3]
I faced stalled data after executing a nested mutation in the last week. As discussed [in this forum post](https://www.graph.cool/forum/t/unable-to-fetch-entity-after-creating-it-in-nested-mutation/2502), I execute a nested mutation and try to load a fresh copy afterwards.

```js
const result = await context.db.mutation.updateInvitation({
    data: {
        status: "ACCEPTED",
        user: {
        create: {
            username: args.data.username,
            password,
            salt,
            emailAddresses: {
            create: {
                primary: true,
                address: args.data.email,
                status: "PENDING",
                verificationCode: createVerificationCode()
            }
            }
        }
        }
    },
    where: {
        id: invitation.id
    }
});

const user = await context.db.query.user({
    where: {
        username: args.data.username
    }
});
```

The `user` object is always `null`. Please note that this is just one scenario. It is basically transferable to each case where you mutate data and try to load it afterwards.

After some digging, I just disabled the cache mechanism of the `dataloader` completely by passing `{cache: false}` to the instantiation: https://github.com/graphcool/http-link-dataloader/blob/325217908a6b799246b648f16c9170c2d4c5628a/src/BatchedGraphQLClient.ts#L17 – This leads to a correct result, but isn't a proper solution for a production environment. I would love to hear your thoughts on establishing a different caching behaviour, like clearing the cache after executing a mutation, etc. What do you think? :)

Reference: https://github.com/facebook/dataloader#clearing-cache

**Edit:**

Some notes about how I disabled the cache in `dataloader`. I edited the `node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js` directly in order to check if disabling the cache fixed my problem – what it did. You have to change the line

```js
this.dataloader = new DataLoader(this.load);
```

to

```js
this.dataloader = new DataLoader(this.load, { cache: false });
```

**Comment by hoodsy** [comment]
@akoenig I'm looking to test your workaround in my app, but am struggling to find where the `DataLoader` is instantiated.

Did you make this change in your `node_modules`?

**Comment by akoenig** [comment]
@hoodsy Ya, had to mention that in the original description. Yes, I edited `node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js` and changed the line

```
this.dataloader = new DataLoader(this.load);
```

to

```
this.dataloader = new DataLoader(this.load, { cache: false });
```

**Comment by nickluger** [comment]
[Data loader](https://github.com/facebook/dataloader) is supposed to be used on a **per request** basis. This is from the docs:

>  Typically, DataLoader instances are created when a Request begins, and are not used once the Request ends.

------------------------------------------------------

So let's see where `http-link-dataloader` is using it. Aha. in the constructor of `BatchedGraphQLClient`: (thanks @akoenig  👍 )

https://github.com/graphcool/http-link-dataloader/blob/a3cd49cae6772945d711bef5967036d8cecce0af/src/BatchedGraphQLClient.ts#L17

which is created once in the constructor of a `HTTPLinkDataLoader` (which is an `ApolloLink`)

------------------------------------------------------

And in the docs here it says:

> That means if you don't want to cache anymore, **just create a new instance of BatchedHTTPLink.**  A good fit for this is every incoming HTTP request in a server environment - on each new HTTP request **a new BatchedHTTPLink instance is created.**

------------------------------------------------------

So the consumer of this `HTTPLinkDataloader` should create it on every request. 

Let's take a look at the code in `prisma-binding`:
```ts
 const httpLink = new HTTPLinkDataloader({
    uri: endpoint,
    headers: { Authorization: `Bearer ${token}` },
  })
```

This piece of code is invoked exactly **once**.  In the constructor of the `Prisma`-binding instance. 

AFAIK this constructor is usually is supposed to be invoked once, too, and not on a per request basis as suggested here. (its the public interface of `prisma-binding`). Is that correct?

This was just a short paperchase trough the repos, but is it correct that `prisma-binding` is using only one instance of `http-link-dataloader`, which is using only one instance of `data-loader` that is caching everything or did i miss something?

**Comment by hoodsy** [comment]
Anyone know how to implement this workaround in a deployed environment? It's difficult to access `node_modules` outside of dev.

**Comment by nickluger** [comment]
For those looking for an interim workaround, as discussed [here](https://github.com/graphcool/prisma-binding/issues/106):
```ts
// instead of this
ctx.db.query.posts({...})
// use this
getPrismaLink().query.posts({...})

// create a new prisma binding instance on demand
export const getPrismaLink = (debug: boolean = false): Prisma => new Prisma({
  endpoint: requiredEnvVars.PRISMA_ENDPOINT
  secret: requiredEnvVars.PRISMA_SECRET, 
  debug: debug 
})
```

**Comment by rickiesmooth** [comment]
this doesn't seem to work with my deployed endpoint

**Comment by brandonmp** [comment]
hm, hitting this problem too on simple mutations w/ `connect` args. @timsuchanek  is this an issue w/ `http-link-dataloader`  ? will rolling back to a previous version of `prisma-binding` help here?

the solution @nickluger  posted doesn't work in my case. 

I run this query to retrieve `user` to check authorization:

```
const getPrismaLink = (): Prisma => 
   new Prisma({
        endpoint: process.env.PRISMA_ENDPOINT,
        secret: process.env.PRISMA_SECRET, 
        debug: true
    });

const QUERY = `{
    id
    email
    purchases {
        item {
            somethingElse {
                id
            }
        }
    }
 }`

const user = getPrismaLink().query.user({ where: { id: 'some-user-id' } }, QUERY)

```

But when I create new a new `purchaseRecord` via this mutation, the record doesn't show up under `user.purchases` until I restart the server:

```
const newPurchaseId = await ctx.db.mutation.createPurchaseRecord(
            {
                data: {
                    pricePaid: storeItem.price,
                    user: { connect: { id: userId } },
                    item: { connect: { id: storeItemId } }
                }
            },
            '{ id }'
        );
```

I haven't tried killing the caching in `http-link-dataloader` b/c i don't want to mess w/ node_modules yet. hoping there's another solution!

**Comment by ramsaylanier** [comment]
👍 I'm also experiencing this issue. Using @nickluger's solution doesn't work - I have to modify node_modules to set caching to false.

**Comment by hoodsy** [comment]
I'm using nick's solution and it works – although without any caching, my app makes a number of duplicate requests

**Comment by gcangussu** [comment]
Had this same issue after updating, rolled back my package.json to the previous version and it fixed it. Currently using prisma-binding@1.3.8, prisma@1.1.2 and graphql-yoga@1.2.1

**Comment by timsuchanek** [comment]
Thanks for reporting everybody! The cache is now disabled by default in the `DataLoader` to prevent these cases.
If you still want the caching activated, you can provide the `cacheResults: true` to the options of the HttpLink.
Prisma Binding `1.5.15` includes this fix.
