### ISSUE TITLE
GraphQL Error (Code: 200)

### ISSUE THREAD

**Issue by hoodsy** [graphcool/http-link-dataloader#4]
Getting this error for all queries/mutations:

```
02/15 02:56 PM  [Network error]: Error: GraphQL Error (Code: 200)
02/15 02:56 PM  Error: GraphQL Error (Code: 200)
                    at BatchedGraphQLClient.<anonymous> (/home/nowuser/src/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:79:35)
                    at step (/home/nowuser/src/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
                    at Object.next (/home/nowuser/src/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
                    at fulfilled (/home/nowuser/src/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
                    at <anonymous>
                    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

This is happening on an instance connected to Prisma Cloud

**Comment by skovhus** [comment]
I get the same error locally... Did you find a solution for this?

**Comment by risjai** [comment]
@hoodsy , how did you solve it?

**Comment by skovhus** [comment]
After debugging, this was caused by changing the name of the service. 😶

**Comment by risjai** [comment]
Even I did that @skovhus, but I did a prisma deploy again after that which should have ideally resolved the issue as the URL changed after that.
So, how did you resolve it, by renaming it back to what it was earlier?

**Comment by skovhus** [comment]
Yes, renaming it back...

I guess we should work on improving the error message here. And fix the underlying issue.

**Comment by risjai** [comment]
Raised a [PR](https://github.com/graphcool/http-link-dataloader/pull/5), to show the underlying error message.

**Comment by marktani** [comment]
I agree that printing the whole error is helpful, thanks for the PR @risjai!

@skovhus, what is the underlying issue in your opinion? I am not quite following.

**Comment by skovhus** [comment]
It seems you cannot rename a project in the prisma.yml file.

**Comment by schickling** [comment]
The error logging should be improved with version `0.1.3` and newer. 🎉

**Comment by marktani** [comment]
@skovhus, did you adjust the endpoint that you connect to after renaming and deploying the changes?

**Comment by skovhus** [comment]
> @skovhus, did you adjust the endpoint that you connect to after renaming and deploying the changes?

No, not updating the .env file was the actual issue. ; )

Great with the new error log! 🍾
